version: "1.0"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: deployer_redis

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
       POSTGRES_PASSWORD: ${DATABASE_URL}
    container_name: deployer_postgres